# Generated by Django 3.0 on 2019-12-16 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stone', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stone',
            name='attribute',
        ),
        migrations.DeleteModel(
            name='attribute',
        ),
        migrations.DeleteModel(
            name='stone',
        ),
    ]
