# Generated by Django 3.0 on 2019-12-20 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stone', '0004_stone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stone',
            name='attribute',
        ),
        migrations.AddField(
            model_name='attribute',
            name='attribute',
            field=models.ManyToManyField(related_name='attribute', to='stone.stone'),
        ),
    ]
