# Generated by Django 3.0 on 2019-12-20 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stone', '0005_auto_20191220_0446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='attribute',
        ),
        migrations.AddField(
            model_name='stone',
            name='attribute',
            field=models.ManyToManyField(related_name='attribute', to='stone.attribute'),
        ),
    ]
