# Generated by Django 3.0 on 2019-12-26 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stone', '0006_auto_20191220_0458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stone',
            name='attribute',
            field=models.ManyToManyField(blank=True, null=True, related_name='attribute', to='stone.attribute'),
        ),
    ]
