# Generated by Django 3.0 on 2019-12-28 10:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stone', '0007_auto_20191226_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='stone',
            name='day_of_mouth',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), default=list, size=None),
        ),
        migrations.AddField(
            model_name='stone',
            name='day_of_week',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stone',
            name='number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
