# Generated by Django 3.0 on 2020-01-07 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stone', '0012_auto_20200107_1853'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
