# Generated by Django 3.0 on 2020-01-08 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stone', '0015_auto_20200108_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='Stone',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stone', to='stone.stone'),
        ),
    ]
