# Generated by Django 3.0 on 2020-01-08 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stone', '0016_auto_20200108_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='password',
            field=models.TextField(blank=True, null=True),
        ),
    ]
