# Generated by Django 3.0 on 2020-01-09 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stone', '0019_favorite_fb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookuserprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
