# Generated by Django 3.0 on 2020-01-09 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stone', '0020_auto_20200109_0441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite_fb',
            name='Stone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stone.stone'),
        ),
    ]
