# Generated by Django 3.0 on 2020-01-10 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stone', '0021_auto_20200109_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='stone',
            name='src_img',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='stone',
            name='stone_img_sm',
            field=models.FileField(blank=True, null=True, upload_to='stone_sm'),
        ),
    ]
