# Generated by Django 3.0 on 2020-01-10 20:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stone', '0022_auto_20200110_0734'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, unique=True, verbose_name='email address')),
                ('dob', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.AddField(
            model_name='stone',
            name='chemical_formula',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
