# Generated by Django 3.0 on 2020-01-10 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stone', '0023_auto_20200110_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stone',
            name='stone_Img',
        ),
        migrations.AddField(
            model_name='stone',
            name='stone_img',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
