# Generated by Django 3.0 on 2020-01-10 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stone', '0024_auto_20200110_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stone',
            name='stone_img_sm',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
