# Generated by Django 3.0 on 2020-01-12 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stone', '0027_auto_20200112_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='stone',
            name='src_img',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
