# Generated by Django 3.0 on 2020-01-12 08:12

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stone', '0028_stone_src_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Startype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(max_length=150)),
                ('day_of_mouth', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), default=list, size=None)),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='stone',
            name='day_of_mouth',
        ),
        migrations.RemoveField(
            model_name='stone',
            name='day_of_week',
        ),
        migrations.RemoveField(
            model_name='stone',
            name='number',
        ),
        migrations.AddField(
            model_name='stone',
            name='star',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stone.Startype'),
        ),
    ]
