# Generated by Django 3.0 on 2020-01-12 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stone', '0029_auto_20200112_0812'),
    ]

    operations = [
        migrations.AddField(
            model_name='startype',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
