# Generated by Django 3.0 on 2020-01-12 09:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stone', '0030_startype_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='startype',
            name='month_of_year',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), default=list, size=None),
        ),
    ]
