# Generated by Django 3.0 on 2020-01-12 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stone', '0032_auto_20200112_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='stone',
            name='day_of_week',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stone',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
