# Generated by Django 3.0 on 2020-01-26 13:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stone', '0033_auto_20200112_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startype',
            name='day_of_mouth',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='startype',
            name='month_of_year',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
    ]
