# Generated by Django 3.0 on 2020-02-03 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stone', '0034_auto_20200126_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stone',
            name='attribute',
            field=models.ManyToManyField(blank=True, null=True, related_name='attribute', to='stone.Attribute'),
        ),
    ]
