# Generated by Django 3.0 on 2020-02-04 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stone', '0035_auto_20200203_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stone',
            name='attribute',
            field=models.ManyToManyField(blank=True, null=True, related_name='attribute', to='stone.Attribute'),
        ),
        migrations.AlterField(
            model_name='stone',
            name='stone_img',
            field=models.ImageField(blank=True, null=True, upload_to='stone'),
        ),
        migrations.AlterField(
            model_name='stone',
            name='stone_img_sm',
            field=models.ImageField(blank=True, null=True, upload_to='stone_sm'),
        ),
    ]
